"""add_verification_fields_to_user

Revision ID: 7bcd52529760
Revises: 
Create Date: 2026-06-01 17:49:17.482646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcd52529760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing production users were created before email verification existed.
    # Backfill them as verified so they can still log in after this migration.
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.alter_column('users', 'is_verified', server_default=sa.false())
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
